version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u admin -p admin --quiet) -eq 1
      interval: 10s
      start_period: 30s

  mongo-express:
    image: "mongo-express:latest"
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/?readConcernLevel=primary
      ME_CONFIG_BASICAUTH_USERNAME: gvinfinity
      ME_CONFIG_BASICAUTH_PASSWORD: administrador
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

volumes:
  mongodb_data_volume:
    external: true